import React from 'react'
import {
  Activity,
  AlertTriangle,
  ArrowDownToLine,
  BarChart3,
  Bell,
  Check,
  ChevronDown,
  CircleDot,
  Clock3,
  Code2,
  Database,
  FileCheck2,
  FileText,
  Filter,
  FolderKanban,
  Gauge,
  GitBranch,
  Layers3,
  LayoutDashboard,
  LifeBuoy,
  MoreHorizontal,
  Play,
  Plus,
  Radar,
  RefreshCw,
  Search,
  Server,
  Settings2,
  ShieldCheck,
  TerminalSquare,
  Upload,
  Users,
  X,
  Zap,
  Cpu,
  Binary,
  ShieldAlert,
  Radio,
  LucideProps,
} from 'lucide-react'

export const iconRegistry: Record<string, React.ComponentType<LucideProps>> = {
  Activity,
  AlertTriangle,
  ArrowDownToLine,
  BarChart3,
  Bell,
  Binary,
  Check,
  ChevronDown,
  CircleDot,
  Clock3,
  Code2,
  Cpu,
  Database,
  FileCheck2,
  FileText,
  Filter,
  FolderKanban,
  Gauge,
  GitBranch,
  Layers3,
  LayoutDashboard,
  LifeBuoy,
  MoreHorizontal,
  Play,
  Plus,
  Radar,
  Radio,
  RefreshCw,
  Search,
  Server,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  TerminalSquare,
  Upload,
  Users,
  X,
  Zap,
}

interface DynamicIconProps extends LucideProps {
  name: string
  fallback?: React.ComponentType<LucideProps>
}

export function DynamicIcon({ name, fallback = Activity, ...props }: DynamicIconProps) {
  const IconComponent = iconRegistry[name] || fallback
  return <IconComponent {...props} />
}
