'use client'

import React, { useState } from 'react'
import { Modal, useToast } from '@/components/ui'
import { api } from '@/lib/api'
import { useDashboard } from '@/providers/dashboard-provider'
import { Loader2, Trash2 } from 'lucide-react'

interface SettingsModalProps {
  isOpen: boolean
  onClose: () => void
}

const OPTIONS: Array<{ key: 'jobs' | 'evidence' | 'reports' | 'results' | 'audit'; label: string; hint: string; defaultOn: boolean }> = [
  { key: 'jobs', label: 'Jobs', hint: 'queued / dispatched / completed job records', defaultOn: true },
  { key: 'evidence', label: 'Evidence', hint: 'collected artifacts, hashes, risk rows', defaultOn: true },
  { key: 'reports', label: 'Reports', hint: 'report-generating jobs (completed/failed) + their artifacts', defaultOn: true },
  { key: 'results', label: 'Agent results', hint: 'raw submissions from endpoints', defaultOn: true },
  { key: 'audit', label: 'Audit log', hint: 'console & API action history', defaultOn: false },
]

export function SettingsModal({ isOpen, onClose }: SettingsModalProps) {
  const { toast } = useToast()
  const { refresh } = useDashboard()
  const [selected, setSelected] = useState<Record<string, boolean>>(
    Object.fromEntries(OPTIONS.map((o) => [o.key, o.defaultOn]))
  )
  const [busy, setBusy] = useState(false)

  const picked = OPTIONS.filter((o) => selected[o.key])

  const handleClear = async () => {
    if (picked.length === 0) {
      toast('Select at least one data category to clear.', 'error')
      return
    }
    const ok = window.confirm(
      `Permanently delete: ${picked.map((p) => p.label).join(', ')}?\n\n` +
        'Agents, JOCKY scripts, users and the schema are kept. This cannot be undone.'
    )
    if (!ok) return
    setBusy(true)
    try {
      const res = await api.adminClearData({
        jobs: selected.jobs,
        evidence: selected.evidence,
        reports: selected.reports,
        results: selected.results,
        audit: selected.audit,
      })
      const detail = Object.entries(res.deleted)
        .map(([k, v]) => `${v} ${k}`)
        .join(', ')
      toast(`Cleared ${detail || 'nothing (already empty)'}.`, 'success')
      await refresh()
      onClose()
    } catch (err) {
      toast(err instanceof Error ? err.message : 'Clear failed', 'error')
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Settings"
      description="Console maintenance — manage the data generated by the platform."
      maxWidth="lg"
    >
      <div className="flex flex-col gap-5 text-xs">
        <section className="flex flex-col gap-3">
          <div>
            <div className="text-[10px] font-bold uppercase tracking-wider text-[#656d76] dark:text-[#8b949e]">
              Data management
            </div>
            <p className="mt-1 text-[11px] leading-snug text-[#656d76] dark:text-[#8b949e]">
              Clear generated records and findings. Endpoint agents, JOCKY scripts, users and the
              database schema are never touched.
            </p>
          </div>

          <div className="flex flex-col gap-1.5">
            {OPTIONS.map((opt) => (
              <label
                key={opt.key}
                className="flex items-start gap-2.5 rounded-md border border-[#d0d7de] dark:border-[#24282F] bg-[#f6f8fa] dark:bg-[#0C0E11] px-3 py-2 cursor-pointer hover:border-[#12A594]/50 dark:hover:border-[#2DD4BF]/40 transition-colors"
              >
                <input
                  type="checkbox"
                  checked={!!selected[opt.key]}
                  onChange={(e) => setSelected((s) => ({ ...s, [opt.key]: e.target.checked }))}
                  className="mt-0.5 size-3.5 accent-[#12A594]"
                />
                <span className="flex-1">
                  <span className="font-bold text-[#1f2328] dark:text-[#e6edf3]">{opt.label}</span>
                  <span className="block text-[10px] text-[#8b949e]">{opt.hint}</span>
                </span>
              </label>
            ))}
          </div>

          <div className="rounded-md border border-rose-300 dark:border-rose-500/40 bg-rose-50 dark:bg-rose-500/10 p-3 flex flex-col gap-2.5">
            <div className="text-[11px] leading-snug text-[#CF222E] dark:text-[#FF8A7A]">
              <strong>Danger zone.</strong> The selected tables are emptied immediately and cannot
              be restored.
            </div>
            <button
              type="button"
              onClick={handleClear}
              disabled={busy}
              className="inline-flex items-center justify-center gap-1.5 rounded-md bg-[#CF222E] dark:bg-[#DA3633] px-3 py-2 text-[11px] font-bold text-white hover:bg-[#A40E26] dark:hover:bg-[#F85149] disabled:opacity-50 transition-colors shadow-2xs cursor-pointer"
            >
              {busy ? <Loader2 className="size-3.5 animate-spin" /> : <Trash2 className="size-3.5" />}
              {busy ? 'Clearing…' : `Clear selected data (${picked.length})`}
            </button>
          </div>
        </section>
      </div>
    </Modal>
  )
}
