"""
Code generator: IR -> Go source.

The generated Go file embeds the IR byte sequence as a self-contained
`func ScriptIR() []byte`, ready to be handed to the Go toolchain or embedded
in an agent binary for fully offline execution.
"""

from typing import Any

from compiler.ir_emitter import ProgramIR, decode_instructions, format_ir


class CodeGenerator:
    def __init__(self, ir_data: Any):
        """
        Accepts: ProgramIR | bytes | bytearray
        """
        if isinstance(ir_data, (bytes, bytearray)):
            self.instructions = decode_instructions(bytes(ir_data))
        elif isinstance(ir_data, ProgramIR):
            self.instructions = ir_data.instructions
        else:
            raise TypeError(f"Unsupported IR input: {type(ir_data)!r}")

    def generate(self) -> str:
        """Generate Go source embedding the IR bytecode."""
        # Re-encode deterministically (keys fixed at 0x01) for reproducible output.
        body = bytearray()
        for ins in self.instructions:
            if ins.op in (0x00, 0x06):
                body.append(ins.op)
                continue
            raw = ins.operand
            key = 0x01
            enc = bytes(b ^ key for b in raw)
            body.append(ins.op)
            body.append(len(enc))
            body.append(key)
            body.extend(enc)

        hex_lines = []
        line = []
        for b in body:
            line.append(f"0x{b:02x}")
            if len(line) == 16:
                hex_lines.append("\t" + ", ".join(line) + ",")
                line = []
        if line:
            hex_lines.append("\t" + ", ".join(line) + ",")

        listing = format_ir(bytes(body))
        header = (
            "// Code generated by JOCKEY CodeGenerator. DO NOT EDIT.\n"
            "// IR listing:\n"
            + "\n".join(f"//   {l}" for l in listing.splitlines())
            + "\n\npackage main\n\n"
            "// ScriptIR returns the polymorphic JOCKY-IR program bytes.\n"
            "func ScriptIR() []byte {\n\treturn []byte{\n"
        )
        footer = "\t}\n}\n"
        return header + "\n".join(hex_lines) + footer
